-- MySQL Script generated by MySQL Workbench
-- Wed 11 Nov 2015 10:59:16 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema little_webshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema little_webshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `little_webshop` DEFAULT CHARACTER SET utf8 ;
USE `little_webshop` ;

-- -----------------------------------------------------
-- Table `little_webshop`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `little_webshop`.`Customer` ;

CREATE TABLE IF NOT EXISTS `little_webshop`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `streetAddress` VARCHAR(45) NULL,
  `postCode` INT NULL,
  `postTown` VARCHAR(45) NULL,
  `phoneNr` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `little_webshop`.`AssetCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `little_webshop`.`AssetCategory` ;

CREATE TABLE IF NOT EXISTS `little_webshop`.`AssetCategory` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `little_webshop`.`Asset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `little_webshop`.`Asset` ;

CREATE TABLE IF NOT EXISTS `little_webshop`.`Asset` (
  `idAsset` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` FLOAT NULL,
  `amountInStore` INT NULL,
  `imagePath` VARCHAR(200) NULL,
  `AssetCategory_idCategory` INT NOT NULL,
  PRIMARY KEY (`idAsset`),
  INDEX `fk_Asset_AssetCategory1_idx` (`AssetCategory_idCategory` ASC),
  CONSTRAINT `fk_Asset_AssetCategory1`
    FOREIGN KEY (`AssetCategory_idCategory`)
    REFERENCES `little_webshop`.`AssetCategory` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `little_webshop`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `little_webshop`.`Order` ;

CREATE TABLE IF NOT EXISTS `little_webshop`.`Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `dateTime` DATETIME NULL,
  `status` INT NULL,
  `Customer_idCustomer` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_Order_Customer_idx` (`Customer_idCustomer` ASC),
  CONSTRAINT `fk_Order_Customer`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `little_webshop`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `little_webshop`.`OrderRow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `little_webshop`.`OrderRow` ;

CREATE TABLE IF NOT EXISTS `little_webshop`.`OrderRow` (
  `idOrderItem` INT NOT NULL AUTO_INCREMENT,
  `orderAmount` INT NULL,
  `Order_idOrder` INT NOT NULL,
  `Asset_idAsset` INT NOT NULL,
  PRIMARY KEY (`idOrderItem`),
  INDEX `fk_OrderItem_Order1_idx` (`Order_idOrder` ASC),
  INDEX `fk_OrderItem_Asset1_idx` (`Asset_idAsset` ASC),
  CONSTRAINT `fk_OrderItem_Order1`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `little_webshop`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_Asset1`
    FOREIGN KEY (`Asset_idAsset`)
    REFERENCES `little_webshop`.`Asset` (`idAsset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
